databases:
  - name: reservations-db
    databaseName: reservations
    user: postgres

services:
  - type: web
    name: restaurant-reservations-api
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: reservations-db
          property: connectionString
    healthCheckPath: /health-check
    disk:
      name: restaurant-reservations-api-disk
      mountPath: /usr/src/app
      sizeGB: 1
  - type: cron
    name: restaurant-reservations-email
    schedule: '0 0 * * *'
    startCommand: 'node sendReservations.js'
    env: node
